# This is a basic workflow to publish a new version of this package.
# It should be triggered on the creation of a new tag.
# It will update the package.json version and publish the package to npm.
# It will finally push a new commit to the master branch that includes the updated package.json version.
name: publish

on:
    push:
        tags:
            - 'v*.*.*'
    workflow_dispatch:
        inputs:
          tag:
            description: 'Tag'
            required: true

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@flocasts'

            - name: Install dependencies
              run: npm ci

            - name: Compile Typescript
              run: npm run build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}